<?php
use Nette\Environment;
use Nette\Application\Routers\Route;
// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . "/../vendor/autoload.php";


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');
if (PHP_SAPI == 'cli') {
    $configurator->setProductionMode(false);
}

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$robot = $configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();
Nella\Console\Config\Extension::register($configurator);
Nella\Doctrine\Config\Extension::register($configurator);
\Kdyby\BootstrapFormRenderer\DI\RendererExtension::register($configurator);
// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section


$container = $configurator->createContainer();
$container->addService('robotLoader', $robot); //needed for presenter tree


Nella\Panels\CallbackPanel::register(array(
    '--robotloader' => array(
        'name' => "Rebuild RobotLoader Cache",
        'callback' => callback($robot, 'rebuild'),
        'args' => array()
    ),
    '--acl' => array(
        'name' => 'Delete ACL cache',
        'callback' => function () {
            Environment::getCache('ACL')->clean(array(Nette\Caching\Cache::TAGS => array('acl')));
        },
        'args' => array()
    ),
    '--menu-cache' => array(
        'name' => 'Delete menu cache',
        'callback' => function () {
            Environment::getCache('Menu')->clean(array(Nette\Caching\Cache::TAGS => array('menu')));
        },
        'args' => array()
    ),
));
$router = $container->application->getRouter();
$router[] = new Route('index.php', 'Dashboard:default', Route::ONE_WAY);
$router[] = new Route('<presenter>/<action>[/<id>]', 'Dashboard:default');

