{snippet grid}

{foreach $flashes as $flash}
<div class="flash {$flash->type}">{$flash->message}</div>
{/foreach}

{widget $control begin}
{widget $control errors}
{widget $control body}
{widget $control end}


<script type="text/javascript">
$("a[data-confirm]").live("click", function(event) {
        
        if (!confirm(this.getAttribute("data-confirm"))) event.preventDefault();
});
</script>

{/snippet}